# Generated by Django 6.1 on 2026-08-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_root', models.CharField(blank=True, help_text='Absolute path, e.g. ~/RideProjects', max_length=1024)),
                ('lm_base_url', models.CharField(default='http://localhost:1234/v1', max_length=300)),
                ('lm_model', models.CharField(blank=True, max_length=200)),
                ('lm_temperature', models.FloatField(default=0.2)),
                ('lm_max_tokens', models.PositiveIntegerField(default=2048)),
                ('mineru_path', models.CharField(default='mineru', max_length=300)),
                ('mineru_timeout', models.PositiveIntegerField(default=900)),
                ('archive_mode', models.CharField(choices=[('move', 'Move'), ('db_only', 'Db Only')], default='move', max_length=8)),
                ('watch_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('file_path', models.CharField(help_text='POSIX path relative to the workspace root', max_length=1024)),
                ('filename', models.CharField(max_length=300)),
                ('extension', models.CharField(blank=True, max_length=16)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('file_mtime', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('doc_kind', models.CharField(choices=[('pdf', 'Pdf'), ('office', 'Office'), ('email', 'Email'), ('cad', 'Cad'), ('image', 'Image'), ('other', 'Other')], default='other', max_length=8)),
                ('doc_type_label', models.CharField(blank=True, help_text='LLM-classified document type', max_length=200)),
                ('extraction_tier', models.CharField(blank=True, choices=[('mineru', 'Mineru'), ('native', 'Native'), ('email', 'Email'), ('metadata', 'Metadata')], max_length=10)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('quality_note', models.CharField(blank=True, help_text='Set when extraction used a fallback path', max_length=300)),
                ('extracted_text', models.TextField(blank=True)),
                ('digest_contribution', models.TextField(blank=True)),
                ('delta_summary', models.TextField(blank=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'document series',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('order', models.PositiveSmallIntegerField()),
                ('extraction_focus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_path', models.CharField(max_length=1024)),
                ('to_path', models.CharField(max_length=1024)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('undone', models.BooleanField(default=False)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='hub.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='hub.documentseries'),
        ),
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('parse', 'Parse'), ('llm', 'Llm'), ('digest', 'Digest'), ('delta', 'Delta')], max_length=8)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=8)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='hub.document')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delta_jobs', to='hub.documentseries')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digest_jobs', to='hub.phase')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='documentseries',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='hub.phase'),
        ),
        migrations.AddField(
            model_name='document',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hub.phase'),
        ),
        migrations.CreateModel(
            name='PhaseDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Markdown')),
                ('model_used', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digest', to='hub.phase')),
            ],
        ),
        migrations.AddField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='hub.project'),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=400)),
                ('mtype', models.CharField(choices=[('gate', 'Gate'), ('decision', 'Decision'), ('deliverable', 'Deliverable'), ('issue', 'Issue'), ('risk', 'Risk'), ('action', 'Action')], default='gate', max_length=12)),
                ('status', models.CharField(choices=[('extracted', 'Extracted'), ('confirmed', 'Confirmed'), ('edited', 'Edited'), ('dismissed', 'Dismissed')], default='extracted', max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('evidence', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='hub.document')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='hub.phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='hub.project')),
            ],
            options={
                'ordering': ['date', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('phase', 'file_path', 'checksum'), name='uniq_doc_path_checksum_per_phase'),
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='uniq_phase_order_per_project'),
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='uniq_phase_slug_per_project'),
        ),
    ]
