# Generated by Django 6.1 on 2026-08-19 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionjob',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to='hub.project'),
        ),
        migrations.AlterField(
            model_name='extractionjob',
            name='kind',
            field=models.CharField(choices=[('parse', 'Parse'), ('llm', 'Llm'), ('digest', 'Digest'), ('delta', 'Delta'), ('report', 'Report')], max_length=8),
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Markdown report body')),
                ('model_used', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hub.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
