# Generated by Django 6.1 on 2026-08-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_tag_alter_extractionjob_kind_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='folder_path',
            field=models.CharField(blank=True, help_text='Workspace-relative folder the question was asked from', max_length=1024),
        ),
    ]
