# Generated by Django 6.1 on 2026-08-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_question_folder_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='hub.milestone'),
        ),
        migrations.AlterField(
            model_name='extractionjob',
            name='kind',
            field=models.CharField(choices=[('parse', 'Parse'), ('llm', 'Llm'), ('digest', 'Digest'), ('delta', 'Delta'), ('report', 'Report'), ('ask', 'Ask'), ('capture', 'Capture')], max_length=8),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('inbox', 'Inbox'), ('filed', 'Filed'), ('skipped', 'Skipped')], default='inbox', max_length=8)),
                ('rationale', models.CharField(blank=True, max_length=400)),
                ('filed_path', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hub.phase')),
                ('suggested_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hub.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='captures', to='hub.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='capture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='hub.capture'),
        ),
    ]
