# Generated by Django 6.1 on 2026-08-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_seed_default_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Set when the phase is closed out', null=True),
        ),
    ]
