# Generated by Django 6.1 on 2026-08-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionjob',
            name='run_after',
            field=models.DateTimeField(blank=True, help_text='Backoff gate: queued job is skipped until this time', null=True),
        ),
    ]
