# Generated by Django 6.1 on 2026-08-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_extractionjob_run_after'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'meeting series',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(default='#FF4F00', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appsettings',
            name='asr_backend',
            field=models.CharField(choices=[('stub', 'stub'), ('funasr_cpu', 'funasr_cpu')], default='funasr_cpu', help_text='Meeting transcription engine; stub needs no models', max_length=12),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('processing', 'Processing'), ('done', 'Done')], default='live', max_length=10)),
                ('audio_path', models.CharField(blank=True, help_text='WAV name under var/meetings/audio/', max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('filed_document', models.ForeignKey(blank=True, help_text='Minutes document created by send-to-phase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='hub.document')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='hub.meetingseries')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Voiceprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField(help_text='192-dim float32 vector')),
                ('sample_path', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiceprints', to='hub.speaker')),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('start_ts', models.FloatField(default=0.0, help_text='Seconds from meeting start')),
                ('end_ts', models.FloatField(default=0.0)),
                ('text', models.TextField(blank=True)),
                ('lang', models.CharField(default='unknown', max_length=8)),
                ('translation', models.TextField(blank=True)),
                ('speaker_label', models.CharField(default='speaker_0', max_length=120)),
                ('is_final', models.BooleanField(default=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='hub.meeting')),
            ],
            options={
                'ordering': ['meeting', 'seq'],
                'unique_together': {('meeting', 'seq')},
            },
        ),
    ]
